version: '3.8'

services:
  ilom-bot:
    build: .
    container_name: ilom-whatsapp-bot
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mongodb://mongodb:27017/ilombot
      - REDIS_URL=redis://redis:6379
      - PORT=3000
    volumes:
      - ./logs:/app/logs
      - ./session:/app/session
      - ./media:/app/media
      - ./backups:/app/backups
      - ./.env:/app/.env:ro
    depends_on:
      - mongodb
      - redis
    networks:
      - ilom-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  mongodb:
    image: mongo:7-jammy
    container_name: ilom-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=ilombot
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD:-password}
    volumes:
      - mongodb_data:/data/db
      - ./backups/mongodb:/backups
    networks:
      - ilom-network
    command: mongod --auth

  redis:
    image: redis:7-alpine
    container_name: ilom-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD:-password} --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    networks:
      - ilom-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    container_name: ilom-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - ilom-bot
    networks:
      - ilom-network

  watchtower:
    image: containrrr/watchtower
    container_name: ilom-watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=3600
      - WATCHTOWER_INCLUDE_STOPPED=true
    command: --interval 3600 ilom-whatsapp-bot

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local

networks:
  ilom-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16